### ISSUE TITLE
Getting Error when running Detection xample

### ISSUE THREAD

**Issue by hanumanhojo** [duangenquan/YoloV2NCS#23]

**Comment by hanumanhojo** [comment]
Hi,
I running the original ncsdk on a PC with Ubuntu 16.04 as the OS.  When I run the Detection Example, this is the error I'm getting:

developer@developer-desktop:~/Movidius/YoloV2NCS$ python3 ./detectionExample/Main.py --video 0
Traceback (most recent call last):
  File "./detectionExample/Main.py", line 5, in <module>
    from ObjectWrapper import *
  File "/home/developer/Movidius/YoloV2NCS/detectionExample/ObjectWrapper.py", line 17, in <module>
    class ObjectWrapper():
  File "/home/developer/Movidius/YoloV2NCS/detectionExample/ObjectWrapper.py", line 18, in ObjectWrapper
    mvnc.global_set_option(mvnc.GlobalOption.RW_LOG_LEVEL, 2)
AttributeError: module 'mvnc.mvncapi' has no attribute 'global_set_option'

**Comment by alekcastillo** [comment]
You're using NCSDK 1. You must use NCSDK 2: https://github.com/movidius/ncsdk/tree/ncsdk2

**Comment by Anvesh-1** [comment]
Hi,
I am using the NCSDK2 provided by you in the comment above but i am still getting the same error,

Traceback (most recent call last):
  File "./detectionExample/Main.py", line 5, in <module>
    from ObjectWrapper import *
  File "/home/YoloV2NCS/detectionExample/ObjectWrapper.py", line 17, in <module>
    class ObjectWrapper():
  File "/home/YoloV2NCS/detectionExample/ObjectWrapper.py", line 18, in ObjectWrapper
    mvnc.global_set_option(mvnc.GlobalOption.RW_LOG_LEVEL, 2)
AttributeError: module 'mvnc.mvncapi' has no attribute 'global_set_option'

**Comment by PINTO0309** [comment]
$ cd ~
$ git clone -b ncsdk2 http://github.com/Movidius/ncsdk
$ cd ncsdk
$ make install
