### ISSUE TITLE
Getting Error when running 

### ISSUE THREAD

**Issue by qingshutie** [duangenquan/YoloV2NCS#25]
Hi,
I have a problem when running detection example:
python3 ./detectionExample/Main.py --image ./data/dog.jpg
Traceback (most recent call last):
  File "./detectionExample/Main.py", line 5, in <module>
    from ObjectWrapper import *
  File "/home/u16/work/YoloV2NCS/detectionExample/ObjectWrapper.py", line 8, in <module>
    importlib.reload(sys)
NameError: name 'sys' is not defined

**Comment by oxfordpelican** [comment]
I have the same problem.. (Ubuntu 16.04)

**Comment by qingshutie** [comment]
change the i to img

**Comment by caizt16** [comment]
@qingshutie maybe you mean "i to idx"?

**Comment by qingshutie** [comment]
@caizt16 yes
