### ISSUE TITLE
Getting Error when running convertyo.sh 

### ISSUE THREAD

**Issue by qingshutie** [duangenquan/YoloV2NCS#26]
./yolomodels/tiny-yolo-voc.cfg
./yolomodels/tiny-yolo-voc.weights
convert yolo to caffe
ERROR:root:region layer is not supported
Traceback (most recent call last):
  File "../python/create_yolo_caffemodel.py", line 8, in <module>
    import caffe
  File "/opt/movidius/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/opt/movidius/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dynamic module does not define init function (init_caffe)
done

**Comment by qingshutie** [comment]
Why region layer is not supported？

**Comment by me6ran** [comment]
I have the same issue,
I have my own trianed model of YOLO, try to convert it, but it is not working. facing this issue.
any idea?
