### ISSUE TITLE
ImportError libpydetector.so: undefined symbol: PyString_Type

### ISSUE THREAD

**Issue by Glennlzk** [duangenquan/YoloV2NCS#29]
Hi, may i know why am I getting an error for the last step?

$ python3.6 ./detectionExample/Main.py --image ./data/dog.jpg
Traceback (most recent call last):
  File "./detectionExample/Main.py", line 5, in <module>
    from ObjectWrapper import *
  File "/home/glenn/workspace/YoloV2NCS/detectionExample/ObjectWrapper.py", line 1, in <module>
    from libpydetector import YoloDetector
ImportError: /home/glenn/workspace/YoloV2NCS/detectionExample/libpydetector.so: undefined symbol: PyString_Type

I currently using ubuntu 18.04. Sorry I am new to ubuntu software.
Currently I have this version:
$ /usr/bin/python3 -V
Python 3.6.5
$ /usr/bin/python -V
Python 2.7.15rc1

**Comment by Glennlzk** [comment]
I have downgrade to Ubuntu 16.04 and it works fine
