### ISSUE TITLE
How to update parameters?

### ISSUE THREAD

**Issue by ichigoi7e** [duangenquan/YoloV2NCS#3]
I want to run my YoloV2 model, but I don't know how to update these parameters: biases, object names, dim, blockwd, targetBlockwd, etc.

Here is my error messages:

Device 0 Address: 1.5 - VID/PID 03e7:2150
Starting wait for connect with 2000ms timeout
Found Address: 1.5 - VID/PID 03e7:2150
Found EP 0x81 : max packet size is 512 bytes
Found EP 0x01 : max packet size is 512 bytes
Found and opened device
Performing bulk write of 865212 bytes...
Successfully sent 865212 bytes of data in 214.377509 ms (3.848960 MB/s)
Boot successful, device address 1.5
Device 0 Address: 1 - VID/PID 03e7:f63b
Found Address: 1 - VID/PID 03e7:f63b
done
Booted 1 -> VSC
/usr/local/lib/python3.5/dist-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
Traceback (most recent call last):
  File "./detectionExample/Main.py", line 34, in <module>
    results = detector.Detect(img)
  File "/home/yanghao2/workspace/ncsdk/ncappzoo/caffe/YoloV2NCS/detectionExample/ObjectWrapper.py", line 80, in Detect
    out = self.Reshape(out, self.dim)
  File "/home/yanghao2/workspace/ncsdk/ncappzoo/caffe/YoloV2NCS/detectionExample/ObjectWrapper.py", line 69, in Reshape
    out = np.transpose(out.reshape(self.wh, int(shape[0]/self.wh)))  
ValueError: cannot reshape array of size 6760 into shape (144,46)

**Comment by ichigoi7e** [comment]
I have solved this issue by myself.
